import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./Providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "IMDb: Ratings, Reviews and Where to Watch the Best Movies & TV Shows ",
  description: "Generated by Nazish using NextJS",
  icons: 'https://img.icons8.com/?size=100&id=ITiDg1AcK044&format=png&color=000000'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
